### ISSUE TITLE
Local Development Linking Support

### ISSUE THREAD

**Issue by holygits** [cennznet/api.js#20]
I'm trying to test some local changes I've made to `@cennznet/api` for use in another project.
I've written jest integration tests but now I'd like to test that the changes don't break my external project.  

Ideally I can do this without publishing the package first.
I've tried `lerna link` etc. but it doesn't seem to work as expected

**Comment by ianhe8x** [comment]
I don't really agree your reason in the beginning, you shouldn't expect or test `@cennznet/api` not breaking your project, but in opposite you project works with a specific version of `@cennznet/api`. If it requires some changes from `@cennznet/api`, you need to submit PR first because there's no guarantee it will be accepted as it is.
If you understand this, you will see there's no need to support linking `@cennznet/api` to a 3rd project.

Though if you really want it, you can build `@cennznet/api` first and run link inside build folder, or if your project uses typescript, you can add paths mapping in your tsconfig.json.

**Comment by holygits** [comment]
Would be nice to add some docs for either approach
